### ISSUE TITLE
lua error wow dragonflight pre-patch 10.0.2

### ISSUE THREAD

**Issue by tucomel** [EKE00372/oUF_Ruri#1]
Message: Interface/AddOns/oUF_Ruri/Nameplates.lua:315: attempt to index local 'mark' (a nil value)
Time: Fri Nov 18 22:50:31 2022
Count: 2
Stack: Interface/AddOns/oUF_Ruri/Nameplates.lua:315: attempt to index local 'mark' (a nil value)
[string "@Interface/AddOns/oUF_Ruri/Nameplates.lua"]:315: in function <Interface/AddOns/oUF_Ruri/Nameplates.lua:309>
[string "@Interface/AddOns/oUF_Ruri/Nameplates.lua"]:593: in function <Interface/AddOns/oUF_Ruri/Nameplates.lua:590>
[string "@Interface/AddOns/oUF/ouf.lua"]:798: in function <Interface/AddOns/oUF/ouf.lua:788>

Locals: self = NamePlate2PlaterUnitFrame {
 UpdateUnitFrame = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9111
 Plater = true
 isNamePlate = true
 HasHideHookRegistered = true
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 TargetNeonDown = Texture {
 }
 powerBar = NamePlate2PlaterUnitFramePowerBar {
 }
 CanCheckAggro = true
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 namePlateIsTarget = true
 ScriptRunInitialization = <function> defined @Interface/AddOns/Plater/Plater.lua:10681
 namePlateUnitToken = "nameplate2"
 aggroGlowUpper = Texture {
 }
 GhostAuraCache = <table> {
 }
 ScriptRunOnShow = <function> defined @Interface/AddOns/Plater/Plater.lua:10642
 namePlateNpcId = 3100
 HookGetInfo = <function> defined @Interface/AddOns/Plater/Plater.lua:10525
 unit = "nameplate2"
 UnregisterEvents = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:8851
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 RegisterEvents = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:8825
 IsUnitNameplate = true
 ExtraIconFrame = NamePlate2PlaterUnitFrameExtraIconRow {
 }
 RefreshID = 6
 namePlateUnitName = "Elder Mottled Boar"
 ScriptRunNoAttach = <function> defined @Interface/AddOns/Plater/Plater.lua:10715
 displayedUnit = "nameplate2"
 HasHooksRegistered = true
 IsUnitEvent = <table> {
 }
 namePlateThreatPercent = 0
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9143
 CheckVehiclePossession = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:8939
 HighlightFrame = NamePlate2PlaterUnitFrameHealthBarHighlightOverlay {
 }
 ScriptRunOnHide = <function> defined @Interface/AddOns/Plater/Plater.lua:10665
 UNIT_PET = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9151
 ScriptHotReload = <function> defined @Interface/AddOns/Plater/Plater.lua:10600
 ScriptRunOnUpdate = <function> defined @Interface/AddOns/Plater/Plater.lua:10622
 castBar2 = NamePlate2PlaterUnitFrameCastBar2 {
 }
 nameplateScaleAdjust = 1
 healthBar = NamePlate2PlaterUnitFrameHealthBar {
 }
 UNIT_NAME_UPDATE = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9131
 BossModIconFrame = NamePlate2PlaterUnitFrameHealthBarBossModIconRow {
 }
 BodyFlashFrame = Frame {
 }
 UpdateName = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9061
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 ActorTitleSpecial = FontString {
 }
 actorType = "enemynpc"
 namePlateClassification = "normal"
 ScriptRunCommMessageHook = <function> defined @Interface/AddOns/Plater/Plater.lua:10692
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 PLAYER_TARGET_CHANGED = <function> defined @Interface/AddOns/WorldQuestTracker/libs/DF/panel.lua:9126
 namePlateInRange = true
 aggroGlowLower = Texture {
 }
 BuffFrame = NamePlate2PlaterUnitFrameBuffFrame1 {
 }
 isBattlePet = false
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 isWidgetOnlyMode = false
 UnitFrameEvents = <table> {
 }
 InExecuteRange = false
 namePlateThreatOffTankIsTanking = false
 namePlateThreatValue = 0
 namePlateUnitReaction = 4
 castBar = NamePlate2PlaterUnitFrameCastBar {
 }
 IsProtected = <function> defined @Inte

**Comment by EKE00372** [comment]
DONT USE another nameplate addon when you already have nameplate modules enable
check yourself addon before post issue next time
