### ISSUE TITLE
Frames do not load as shadow priest

### ISSUE THREAD

**Issue by Elegant996** [EKE00372/oUF_Ruri#2]
**Describe the bug**
Unit frames do not load for shadow priest on latest R4.1.

**To Reproduce**
按步驟具體地描述如何重現這個bug。
1.  Install addon fresh
2.  Login as shadow priest
3.  Frames do not show (no LUA error)

**Check before post**
Will bug still exists when only oUF and oUF_Ruri enable?
在禁用了所有插件只啟用oUF和oUF_Ruri的情況下，是否仍會有這個問題？

Yes

**Lua Error**
Post lua error log if you have.
如果有lua錯誤，請貼上。

No error; player unit frame is invisible and target frame is not loaded. Issue appears to be with how the player unit frame is created.

**Screenshots**
如果有，請上傳一張BUG的截圖。

**Comment by EKE00372** [comment]
fixed by commit 553ed6f

if issue still, reopen this ticket.

還有問題再重新打開
